name: FrontBot

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # every sunday at 0:00

jobs:
    frontbot:
        uses: janpecha/actions/.github/workflows/frontbot.yml@master
        secrets:
            FRONTBOT_TOKEN: ${{ secrets.FRONTBOT_TOKEN }}
